name: softgym-py3.8
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - geos
  - pip:
    - pybind11==2.11.1
    - numpy
    - imageio
    - matplotlib
    - moviepy==1.0.3
    - joblib
    - opencv-python
    - Shapely==1.6.4.post2
    - pyquaternion
    - sk-video
    - pillow
    - gym
    - pandas
    - gdown
    - dotmap