name: softgym
channels:
  - defaults
dependencies:
  - python=3.7.7
  - cmake=3.14.0
  - pybind11=2.4.3
  - pip
  - pip:
    - numpy==1.21.5
    - imageio==2.16.1
    - matplotlib==3.5.3
    - moviepy
    - joblib==1.1.0
    - opencv-python==4.1.1.26
    - Shapely==1.6.4.post2
    - pyquaternion==0.9.5 
    - sk-video==1.1.10
    - pillow==9.0.1
    - gym==0.23.1
    - pandas==1.3.5
    - gdown==4.7.3